version: '3.2'

services:
  db:
    image: mysql:8.0.14
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      DATABASE_HOST: 'localhost'
    ports:
      - "3306:3306"
    volumes:
      - /home/tester/data/mysqlDb:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 6061:8080

